version: "3.7"

services:

  nginx:
    build: .
    ports:
      - "8080:80"
      - "6387:6387"
    environment:
      SERVICE_HOST: real_nginx
      SERVICE_PORT: "80"


  real_nginx:
    image: nginx:1.16-alpine
