FROM nginx:1.16-alpine

# dnsmasq is required to be able to resolve via hosts file
RUN apk --no-cache add dnsmasq

COPY scripts.dnsmsq /scripts
RUN chmod a+x /scripts/*.sh

WORKDIR /scripts

ENV SERVICE_HOST dummy
ENV SERVICE_PORT 80

CMD ./start.sh
